### PR TITLE
The formatter plugin is in options id, not type.

### PR DESCRIPTION
**Pull request by Berdir**
Not sure why the tests didn't catch this, the first problem that I saw was that there were no settings (aka, it fell back to the default formatter which had no settings in my case).

### CODE REVIEW

**Comment by davereid** [comment]
I'm confused, I don't see 'id' being referenced anywhere else?

**Comment by Berdir** [comment]
Had another look.

The problem is that type is only set in prepareFormatters() but that's not used in settingsForm(). However, id is part of the standard plugin definition, so I don't see a reason to not simply use that. Removed the type default in prepareFormatters() too.

**Comment by Berdir** [comment]
Bump ;)

This contains a few more fixes now, not sure if it should be split up, happy to do that if you'd prefer that.

**Comment by slashrsm** [comment]
Thanks!

**Pull request merged**
